// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDuc69LpYhpEMOMd8gJJPzWjUMBFvIlgB8',
    appId: '1:1058590959649:web:a518d7737bebdad0811b60',
    messagingSenderId: '1058590959649',
    projectId: 'dateapp-7e7fe',
    authDomain: 'dateapp-7e7fe.firebaseapp.com',
    storageBucket: 'dateapp-7e7fe.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCAsJ3bFusP-72bBAInco011Nug8wmviWY',
    appId: '1:1058590959649:android:272ceb8b7126a5b8811b60',
    messagingSenderId: '1058590959649',
    projectId: 'dateapp-7e7fe',
    storageBucket: 'dateapp-7e7fe.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCE4WIlU6uEAuNALuGAriS6EIFhqgpNMdk',
    appId: '1:1058590959649:ios:de3264a4d5d09629811b60',
    messagingSenderId: '1058590959649',
    projectId: 'dateapp-7e7fe',
    storageBucket: 'dateapp-7e7fe.appspot.com',
    iosClientId: '1058590959649-f2p0qcv2cjmell9nic4p2a5pnekae2na.apps.googleusercontent.com',
    iosBundleId: 'com.example.dateapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCE4WIlU6uEAuNALuGAriS6EIFhqgpNMdk',
    appId: '1:1058590959649:ios:de3264a4d5d09629811b60',
    messagingSenderId: '1058590959649',
    projectId: 'dateapp-7e7fe',
    storageBucket: 'dateapp-7e7fe.appspot.com',
    iosClientId: '1058590959649-f2p0qcv2cjmell9nic4p2a5pnekae2na.apps.googleusercontent.com',
    iosBundleId: 'com.example.dateapp',
  );
}
